drivers: Fix bad function prototypes
../drivers/misc/wl2866d.c:79:34: error:   CC      drivers/net/ethernet/qualcomm/rmnet/rmnet_vnd.o
  CC      drivers/gpu/drm/msm/dp/dp_usbpd.o
a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int wl2866d_camera_power_down_all()
                                 ^
                                  void

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.c:1320:34: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:91:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
3 errors generated.

Signed-off-by: Richard Raya <rdxzv.dev@gmail.com>